name: App Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE'
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') && github.repository_owner == 'Kry9toN' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Write key
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          touch local.properties
          echo apiKey=${{ secrets.API_KEY }} >> local.properties
          echo storePassword=${{ secrets.KEYSTORE_PASSWORD }} >> local.properties
          echo keyAlias=${{ secrets.KEYSTORE_ALIAS }} >> local.properties
          echo keyPassword='${{ secrets.KEYSTORE_ALIAS_PASSWORD }}' >> local.properties
          echo storeFile=../keystore-signature.jks >> local.properties
          echo ${{ secrets.KEYSTORE }} | base64 --decode > keystore-signature.jks
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-app-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps
      - name: Cache Gradle Build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-app-${{ github.sha }}
          restore-keys: |
            gradle-builds
      - name: Build with Gradle
        id: buildWithGradle
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew :app:assembleRelease :app:assembleDebug app:bundleRelease
          echo "::set-output name=releaseName::`ls app/build/outputs/apk/release/*.apk | awk -F '(/|.apk)' '{print $6}'`"
          echo "::set-output name=debugName::`ls app/build/outputs/apk/debug/*.apk | awk -F '(/|.apk)' '{print $6}'`"
          echo "::set-output name=bundleName::`ls app/build/outputs/bundle/release/*.aab | awk -F '(/|.aab)' '{print $6}'`"
      - name: Upload release
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.buildWithGradle.outputs.releaseName }}
          path: "app/build/outputs/apk/release/*.apk"
      - name: Upload debug
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.buildWithGradle.outputs.debugName }}
          path: "app/build/outputs/apk/debug/*.apk"
      - name: Upload bundle
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.buildWithGradle.outputs.bundleName }}
          path: "app/build/outputs/bundle/release/*.aab"
      - name: Upload mappings
        uses: actions/upload-artifact@v2
        with:
          name: mappings
          path: "app/build/outputs/mapping/release"
      - name: Upload native code
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: native-code
          path: "app/build/intermediates/merged_native_libs/release/out/lib/*"
